config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, :only => [:show] do
    resources :projects, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :projects do
    resources :nodes, :only => [:create, :update, :destroy] 

    resources :requests, :only => [:create, :edit, :update, :destroy] 

    get 'max_flow'

    get 'show_request_form'

    get 'start'
  end

  resources :connections, :only => [:create, :update, :destroy] do
    get 'delete_by_nodes', :on => :collection
  
    get 'find_by_nodes', :on => :collection
  end

  root :to => 'projects#index' 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :projects
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :show
end

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Залогиниться", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Зарегистрироваться", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Забыли пароль?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Не получили инструкции для подтверждения емейла?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Зайти через #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>