config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, :only => [:show] do
    resources :projects, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :projects do
    resources :nodes, :only => [:create, :update, :destroy] 

    resources :requests, :only => [:create, :edit, :update, :destroy] 

    get 'max_flow'

    get 'show_request_form'

    get 'start'
  end

  resources :connections, :only => [:create, :update, :destroy] do
    get 'delete_by_nodes', :on => :collection
  
    get 'find_by_nodes', :on => :collection
  end

  root :to => 'projects#index' 
end

app/views/shared/_add_node.html.erb
<%= link_to 'Добавить ноду', project_nodes_url(project, :node => { 
  :left => (((project.nodes.count % 3) == 0) ? 0 : (project.nodes.count % 3)) * 240, 
  :top => (project.nodes.count / 3) * 140 }), 
  :remote => true, :method => :post, :id => 'add_node', :class => 'btn', :id => 'add_node' %>

app/views/shared/_add_request.html.erb
<div id="add_request" style="display:none;"class="modal" tabindex="-1"
  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    
    <h3 id="myModalLabel">Создать запрос</h3>
  </div>

  <div class="modal-body"> 
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; Копылов Герман 2015</p>
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        
        <span class="icon-bar"></span>
      </a>

      <%= link_to 'FlowMaximization', root_url, :class => 'brand' %>

      <div class="container-fluid nav-collapse">
        <%= render 'shared/login' %>

        <ul class="nav">
          <li><%= link_to 'Проекты', projects_url  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Вы вошли как <%= link_to current_user.email, current_user %> | 
    <%= link_to 'Выйти', destroy_user_session_url %>
  <% else %>
    <%= link_to 'Зарегистрироваться', new_user_registration_url %>
      или
    <%= link_to 'залогиниться', new_user_session_url %>
  <% end %>
</p>

app/views/shared/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <h3>О приложении</h3>

    <p>Это приложение было написано с использованием ruby и фреймворка ruby on rails 
      для научной работы в области максимизации потока в сети</p>
  </div><!--/.well -->
</div><!--/span-->