config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, :only => [:show] do
    resources :projects, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :projects do
    resources :nodes, :only => [:create, :update, :destroy] 

    resources :requests, :only => [:create, :edit, :update, :destroy] 

    get 'max_flow'

    get 'show_request_form'

    get 'start'
  end

  resources :connections, :only => [:create, :update, :destroy] do
    get 'delete_by_nodes', :on => :collection
  
    get 'find_by_nodes', :on => :collection
  end

  root :to => 'projects#index' 
end

app/models/request.rb
# encoding: utf-8

class Request < ActiveRecord::Base
  belongs_to :source, :foreign_key => :source_id, :class_name => 'Node'

  belongs_to :target, :foreign_key => :target_id, :class_name => 'Node'

  belongs_to :project

  validates :target_id, :source_id, :presence => true

  validates :start_time, :lifetime, :size, :presence => true, 
    :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }

  validate :source_and_target_validation

  #attr_accessible :lifetime, :size, :source_id, :target_id, :project_id, :start_time, :success, :path

  #@TODO spec me
  def push_request
    if (project.max_flow source_id, target_id, start_time) < size
      update_attribute :success, false
    else
      request_size = self.size

      while request_size > 0
        timer = Timer.where(:time => start_time, :project_id => project.id).first_or_create

        if timer.capacities_matrix_text.present?
          capacities_matrix = eval(timer.capacities_matrix_text)
        else
          capacities_matrix = (project.connections_hashes start_time).last

          timer.capacities_matrix_text = capacities_matrix.to_s
        end

        timer.save
        
        best_path = project.best_path source_id, target_id, start_time

        capacities_matrix = eval((timer = project.timers.where(:time => self.start_time).first).capacities_matrix_text)

        min_capacity = []

        best_path.each_cons(2).to_a.each do |source_id, target_id|
          min_capacity << capacities_matrix[source_id][target_id] 
        end
  
        min_capacity = min_capacity.min

        min_capacity = min_capacity > request_size ? request_size : min_capacity
       
        (self.start_time..(self.start_time + self.lifetime - 1)).each do |time|
          timer = Timer.where(:time => time, :project_id => project.id).first_or_create

          if timer.capacities_matrix_text.present?
            capacities_matrix = eval(timer.capacities_matrix_text)
          else
            capacities_matrix = (project.connections_hashes time).last
          end
        
          best_path.each_cons(2).to_a.each do |source_id, target_id|
            capacities_matrix[source_id][target_id] -= min_capacity 
          end

          timer.capacities_matrix_text = capacities_matrix.to_s

          timer.save
        end

        update_attribute :path, path.to_s + best_path.to_s

        request_size -= min_capacity
      end

      update_attribute :success, true
    end
  end

  private
  def source_and_target_validation
    if source_id == target_id
      errors.add(:source_id, 'Источник и сток не могут быть одиниковы')
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  load_and_authorize_resource :project

  load_and_authorize_resource :request, :through => :project

  def create
    if @request.save
      render
    else
      render :js => 'alert("There are some errors that prevents to save the request");'
    end
  end

  def update
    if @request.update_attributes(resource_params)
      render
    else
      render :js => 'alert("There are some errors that prevents to update the request");'
    end
  end

  def destroy
    if @request.destroy
      render
    else
      render :js => 'alert("There are some errors that prevents to destroy the request");'
    end
  end

  private

  def resource_params
    params.require(:request).permit(:lifetime, :size, :source_id, :target_id, :project_id, :start_time, :success, :path)
  end
end

app/views/requests/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  
  <h3 id="myModalLabel">Свойства канала</h3>
</div>

<div class="modal-body"> 
  <%= form_for [project, request], :remote => true, :html => { :class => "form-horizontal" } do |f| %>
    <% if request.errors.any?  %>
      <div class="alert alert-block alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>

        <h4>При сохранинии запроса произошли ошибки</h4>

        <% request.errors.full_messages.each do |error| %>
          <p><%= error %></p>
        <% end %>
      </div>
    <% end %>

    <div class="control-group">
      <label class="control-label" for="inputSize">Размер</label>

      <div class="controls">
        <%= f.text_field :size, :id => 'inputSize' %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="inputLifetime">Время жизни</label>
      
      <div class="controls">
        <%= f.text_field :lifetime, :width => 100 %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="inputLifetime">Источник</label>
      
      <div class="controls">
        <%= collection_select(:request, :source_id, project.nodes, :id, :id) %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="inputLifetime">Сток</label>
      
      <div class="controls">
        <%= collection_select(:request, :target_id, project.nodes, :id, :id) %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="inputLifetime">Время поступления</label>
      
      <div class="controls">
        <%= f.text_field :start_time, :width => 100 %>
      </div>
    </div>

    <div class="modal-footer">
      <%= f.submit :class => 'btn btn-primary pull-left'  %>
    </div>
<% end %>
</div>

app/views/requests/_request.html.erb
<div class="well well-small" id="request_<%= request.id %>">
  <% if can? :delete, request %>
    <%= link_to '&times;'.html_safe, project_request_url(request.project, request), 
      :method => 'delete', :confirm => 'Вы уверены, что хотите удалить запрос?', :class => 'close', :remote => true %>
  <% end %>

  <% if can? :edit, request %>
    <%= link_to '<i class="icon-pencil"></i>&nbsp;'.html_safe, edit_project_request_url(request.project, request), 
      :class => 'pull-right', :remote => true %>
  <% end %>

  Id: <%= request.id %><br>
  
  Исток: <%= request.source_id %><br>

  Сток: <%= request.target_id %><br>

  Размер: <%= request.size %><br>

  Время жизни: <%= request.lifetime %><br>

  Время поступления: <%= request.start_time %>
</div>

app/views/requests/create.js.erb
<% if @request.errors.any? %>
  $('#request_form').html('<%= j (render 'requests/form', :project => @project, :request => @request) %>');
              
  $('#request_form').modal();
<% else %>
  $('#requests').append('<%= j (render 'request', :request => @request) %>');

  $('#request_form').modal('hide');
<% end %>

app/views/requests/destroy.js.erb
$('#request_<%= @request.id %>').remove();

app/views/requests/edit.js.erb
$('#request_form').html('<%= j (render 'requests/form', :project => @project, :request => @request) %>');
            
$('#request_form').modal();

app/views/requests/update.js.erb
<% if @request.errors.any? %>

<% else %>
  $('#request_<%= @request.id %>').replaceWith('<%= j (render 'request', :request => @request) %>');

  $('#request_form').modal('hide');
<% end %>