config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, :only => [:show] do
    resources :projects, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :projects do
    resources :nodes, :only => [:create, :update, :destroy] 

    resources :requests, :only => [:create, :edit, :update, :destroy] 

    get 'max_flow'

    get 'show_request_form'

    get 'start'
  end

  resources :connections, :only => [:create, :update, :destroy] do
    get 'delete_by_nodes', :on => :collection
  
    get 'find_by_nodes', :on => :collection
  end

  root :to => 'projects#index' 
end

app/models/project.rb
require 'push_relable'
require 'dijkstra'

class Project < ActiveRecord::Base
  include PushRelable
  include Dijkstra

  belongs_to :user

  has_many :nodes, :dependent => :destroy

  has_many :requests, :dependent => :destroy

  has_many :timers, :dependent => :destroy

  validates :user_id, :presence => true   
 
  validates :name, :presence => true, :uniqueness => true

  #attr_accessible :name, :user_id

  #@TODO spec me
  def capacities_matrix source_id, target_id, time=false
    capacities = []

    connections_hash, connections_double_hash = connections_hashes time

    matching_array = reorder_nodes connections_hash, source_id, target_id

    connections_hash.each do |source_id, target_array|
      capacities[matching_array[source_id]] = []

      target_array.each do |target_id|
        if source_id.present? && target_id.present? && connections_double_hash[source_id].present?
          capacities[matching_array[source_id]][matching_array[target_id]]= connections_double_hash[source_id][target_id]
        end
      end
    end
    
    capacities.count.times do |i|
      capacities.count.times do |j|
        capacities[i][j] = (capacities[i].present? && capacities[i][j].present?) ? capacities[i][j] : 0
      end
    end

    capacities
  end

  #@TODO spec me
  def costs_graph time=false
    connections_hash = {}

    self.nodes.includes(:nodes).each do |source| 
      connections_hash[source.id] = []

      source.nodes.each do |target|
        connections_hash[source.id] << target.id
      end
    end

    connections = Connection.where(:source_id => connections_hash.keys).
      where(:target_id => connections_hash.values.flatten.uniq)

    connections_double_hash = {}

    if time.present? && (timer=self.timers.where(:time => time).first).present?
      connections_double_hash_capacities = eval(timer.capacities_matrix_text)

      connections.each do |connection|
        if connections_double_hash_capacities[connection.source_id][connection.target_id] > 0
          connections_double_hash[connection.source_id] ||= {}

          connections_double_hash[connection.source_id][connection.target_id] = connection.cost
        end
      end
    else
      connections.each do |connection|
        connections_double_hash[connection.source_id] ||= {}

        connections_double_hash[connection.source_id][connection.target_id] = connection.cost
      end
    end

    connections_double_hash
  end

  def connections_hashes time=false
    connections_hash = {}

    self.nodes.includes(:nodes).each do |source| 
      connections_hash[source.id] = []

      source.nodes.each do |target|
        connections_hash[source.id] << target.id
      end
    end

    connections = Connection.where(:source_id => connections_hash.keys).
      where(:target_id => connections_hash.values.flatten.uniq)

    connections_double_hash = {}

    if (timer = self.timers.where(:time => time).first).present?
      connections_double_hash = eval(timer.capacities_matrix_text)
    else
      connections.each do |connection|
        connections_double_hash[connection.source_id] ||= {}

        connections_double_hash[connection.source_id][connection.target_id] = connection.capacity
      end
    end

    [connections_hash, connections_double_hash]
  end

  def start
    self.reload.timers.destroy_all

    requests.order("start_time ASC").each do |request|
      request.update_attribute :path, ''
      
      request.push_request
    end
  
    self.reload.timers.destroy_all
  end

  private
  def reorder_nodes connections_hash, source_id, target_id
    ordered_hash = (connections_hash.keys + connections_hash.values.flatten).uniq.sort

    counter = 0

    matching_array = {}

    ordered_hash.delete source_id

    ordered_hash.delete target_id

    ordered_hash.insert(0, source_id)

    ordered_hash.insert(-1, target_id)

    ordered_hash.each do |node_id|
      matching_array[node_id] = counter 
    
      counter += 1
    end

    matching_array
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  load_and_authorize_resource :user

  load_and_authorize_resource :project, :through => :user, :shallow => true

  def index 
    @projects = Project.includes(:user).order('created_at desc').page params[:page]
  end

  def create
    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    if @project.update_attributes(resource_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_url
    else
      render :index
    end
  end

  def max_flow
    @project = Project.find params[:project_id]

    @max_flow = @project.max_flow
  end

  def show_request_form
    @project = Project.find params[:project_id] 
  end

  def start
    @project = Project.find params[:project_id]

    @requests = @project.start
  end

  private

  def resource_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_display_connections.html.erb
$(function () {
  <% connections_hash, connections_double_hash = @project.connections_hashes %>

  <% costs_graph = @project.costs_graph %>

  jsPlumb.setSuspendDrawing(true);

  <% connections_hash.each do |source_id, target_array| %>
    <% target_array.each do |target_id| %>
      <% if source_id.present? && target_id.present? %> 
        jsPlumb.connect({
          source:"node_<%= source_id %>", 
          target:"node_<%= target_id %>"
          }).getOverlay("label").
            setLabel('<%= connections_double_hash[source_id][target_id] %>/<%= costs_graph[source_id][target_id] %>');
      <% end %>
    <% end %>
  <% end %>

  jsPlumb.setSuspendDrawing(false, true);
});

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div class="alert alert-block">
    <h4>При сохранении проекта произошла ошибка</h4>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@user, @project], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/_nodes.html.erb
<div id="demo">
  <%= render @project.nodes %>
</div>

app/views/projects/_request.html.erb
<div class="requests" id="request_<%= request.id %>">
  Id: <%= request.id %><br>
  
  Исток: <%= request.source_id %><br>

  Сток: <%= request.source_id %><br>

  Размер: <%= request.size %><br>

  Время жизни: <%= request.lifetime %>
</div>

app/views/projects/_requests.html.erb
<div id="requests">
  <%= render @project.requests %>
</div>

app/views/projects/_results.html.erb
<div class="well well-small">
  <p>Общее число запросов: <%= project.requests.size %></p>

  <p>Количество пройденных запросов: <%= project.requests.where(:success => true).size %></p>

  <p>Количество непройденных запросов: <%= project.requests.where('success != ?', true).size %></p>

  <table class="table">
    <thead>
      <tr>
        <th>Запрос №</th>

        <th>Пройден</th>

        <th>Путь</th>
      </tr>
    </thead>
  
    <% project.requests.each do |request| %>
      <tr>
        <td><%= request.id %></td>
        
        <td><%= request.success == true ? 'Да' : 'Нет' %></td>
        
        <td><%= request.path %></td>
      </tr>
    <% end %> 
  </table>
</div>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>
    <%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %>
  </h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1>Проекты</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.name %></td>
        <td><%=l project.created_at, :format => :long %></td>
        <td>
          <% if can? :manage, project %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), 
              edit_project_path(project), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project),
              :method => :delete, 
              :data => { :confirm => t('.confirm',:default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @projects %>

<% if can? :create, Project %>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_user_project_path(current_user), :class => 'btn btn-primary' %>
<% end %>

app/views/projects/max_flow.js.erb
alert('<%= @project.max_flow %>')

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  
  <dd><%= @project.user_id %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  
  <dd><%= @project.name %></dd>
</dl>

<% if can? :manage, @project %>
  <div class="form-actions text-center">
    <div class="btn-group">
      <%= link_to t('.back', :default => t("helpers.links.back")), projects_path, :class => 'btn'  %>

      <%= render 'shared/add_node', :project => @project %>

      <%= link_to "Добавить запрос", project_show_request_form_url(@project), :class => 'btn', :remote => true %>

      <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(@project), :class => 'btn' %>
     
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(@project),
        :method => 'delete', 
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-danger' %>

        <%= link_to "Построить сеть с потоками", project_start_url(@project), :class => 'btn', :remote => true,
          :onclick => "$(this).toggleClass('loading')", :id => 'start_button' %>
    </div>
  </div>
<% end %>

<div id="results"></div>

<div class="row-fluid">
  <div class="span9">
    <h4 class="text-center">Ноды</h4>

    <%= render 'nodes' %>
  </div>

  <div class="span3">
    <h4 class="text-center">Запросы</h4>

    <%= render 'requests' %>
  </div>
</div>

<% content_for :js do %>
  <%= javascript_tag do %>
    $(function() { <%= render 'display_connections' %> });

    $(document).on('page:load', function() { <%= render 'display_connections' %> });
  <% end %>
<% end %>

app/views/projects/show_request_form.js.erb
$('#request_form').html('<%= j (render 'requests/form', :project => @project, :request => @project.requests.build) %>');
            
$('#request_form').modal();

app/views/projects/start.js.erb
$('#results').html('<%= j render 'results', :project => @project %>');

$('#start_button').removeClass('loading');